[colors.normal]
black = "0x1c1f24"
blue = "0x51afef"
cyan = "0x5699af"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xdfdfdf"
yellow = "0xda8548"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[colors.selection]
text = "0xbbc2cf"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "Mononoki Nerd Font"

[window.padding]
x = 0
y = 0
[window]
opacity = 1
